baseurl: /
url: http://99gas.com
defaults:
  -
    scope:
      path: ""
    values:
      title: 99gás
      revenda_dashboard_url: http://web.staging.99gas.com
      cidades: cidades.html
      como: como.html
      contato: contato.html
      sobre: sobre.html
      termos: termos.html